apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wiki-claim
  labels:
    app: wikimedia
    role: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi