# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-initdb-pv-claim
#   labels:
#     app: wikimedia
#     role: db
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mysql/db1/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wiki-claim
  labels:
    app: wikimedia
    role: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi