apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: wikimedia
    role: admin
spec:
  selector:
    matchLabels:
      app: wikimedia
      role: admin
  template:
    metadata:
      labels:
        app: wikimedia
        role: admin
    spec:
      containers:
      - name: pma
        image: phpmyadmin:latest
        env:
          - name: PMA_HOST
            value: "mysql"
          - name: PMA_PORT
            value: "3306"
        ports:
          - containerPort: 80
            name: http
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "0.3"
      #   volumeMounts:
      #     - name: mediawiki-localsettings
      #       mountPath: /var/www/html/LocalSettings.php
      # volumes:
      #   - name: mediawiki-localsettings
      #     hostPath:
      #       path: /Users/Nicolas/Documents/k8s/ETRS712/LocalSettings.php
      #       type: File

