apiVersion: v1
kind: Service
metadata:
  name: pma
  labels:
    app: wikimedia
    role: admin
spec:
  selector:
    app: wikimedia
    role: admin
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 32124

