apiVersion: v1
kind: Service
metadata:
  name: wiki
  labels:
    app: wikimedia
    role: front
spec:
  selector:
    app: wikimedia
    role: front
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32123

